### ISSUE TITLE
Allow logo/link customization

### ISSUE THREAD

**Issue by jdlrobson** [Wikimedia-AU/MediaWiki-skin#22]
It would be nice if the skin could be used outside Wikimedia AU.

For logo: it should be possible to use `$wgLogos['wordmark']` instead of the hardcoded SVG.

The footer could be configurable by wiki page or Hooks::SkinAddFooterLinks

Possibly something to be left to the end of the project, so you can focus on your main objective?

**Comment by samwilson** [comment]
Yes that sounds like a good idea. I've been wondering about renaming it as well. The three menus could be defined in e.g. `MediaWiki:WMAU-skin.json` (I know they could sort of be done in `MediaWiki:Sidebar` but then they couldn't easily define their icons, and at the moment I want the skin to not need any changes to anything that Vector is using, so it can be installed alongside without drama).

It sounds like the top horizontal logo can be the `wordmark`, so maybe the bottom one can be the logo (i.e. `1x` etc. from `$wgLogos`). Or are we allowed to create extra keys in the config var, e.g. `$wgLogos['footer-logo']`?

**Comment by jdlrobson** [comment]
wgLogos can contain `wordmark`, `icon`, and `tagline`. I think `icon` is what you want for the footer not `1x`

You can add non-standardized keys, but use the standardized ones wherever possible.

Feel free to update https://www.mediawiki.org/wiki/Manual:$wgLogos if anything looks out of whack in the documentation!

**Comment by samwilson** [comment]
Done.
